unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

# mouseForScroll
set -g mouse on

# make it vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -n C-d send-keys ''

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'



## conf

set -g @rose_pine_only_window 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_right_separator " "
set -g @rose_pine_window_status_separator " "
set -g status-justify centre
#set -g @rose_pine_only_windows 'on'

# conf

run '~/.tmux/plugins/tpm/tpm'
