####
# Control + Space is Main-Key/Prefix for any
####
set -g prefix C-Space
unbind C-b

bind C-Space send-prefix

unbind r
bind r source-file ~/.tmux.conf


# mouseForScrol:
set -g mouse on

# make it vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -n C-M-S-x kill-server

bind -n C-d send-keys ''
set -g status-justify centre

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'rose-pine/tmux'

#set -g @rose_pine_variant 'dawn'

## conf

set -g @rose_pine_only_windows 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_window_status_separator " | "

set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disable_color_options 'default'

# conf

run '~/.tmux/plugins/tpm/tpm'
